# Generated by Django 5.1.6 on 2025-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='descriptions',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=250),
        ),
    ]
