# Generated by Django 5.1.6 on 2025-02-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_questions_descriptions_alter_questions_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='number',
        ),
    ]
